# Generated by Django 4.2.7 on 2025-10-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Menyu Mahsuloti', 'verbose_name_plural': 'Menyu Mahsulotlari'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Kategoriyadagi tartib raqami'),
        ),
    ]
