# Generated by Django 4.2.7 on 2025-10-02 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='linked_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='menu.menuitem'),
        ),
    ]
