# Generated by Django 4.2.7 on 2025-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_options_menuitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['global_order', 'name'], 'verbose_name': 'Menyu Mahsuloti', 'verbose_name_plural': 'Menyu Mahsulotlari'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category_order',
            field=models.PositiveIntegerField(default=0, help_text="Faqat o'z kategoriyasi ichidagi tartib"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='global_order',
            field=models.PositiveIntegerField(default=0, help_text='Barcha taomlar orasidagi umumiy tartib (Hammasi kategoriyasi uchun)'),
        ),
    ]
