# Generated by Django 4.2.7 on 2025-10-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_promotion_linked_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Savatcha Mahsuloti', 'verbose_name_plural': 'Savatcha Mahsulotlari'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Menyu Mahsuloti', 'verbose_name_plural': 'Menyu Mahsulotlari'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyurtma Mahsuloti', 'verbose_name_plural': 'Buyurtma Mahsulotlari'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aksiya', 'verbose_name_plural': 'Aksiyalar'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date'], 'verbose_name': 'Sharh', 'verbose_name_plural': 'Sharhlar'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Sayt Sozlamasi', 'verbose_name_plural': 'Sayt Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='textcontent',
            options={'ordering': ['content_type', 'order', 'key'], 'verbose_name': 'Matn Kontenti', 'verbose_name_plural': 'Matn Kontentlari'},
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], help_text='Action performed on review', max_length=20)),
                ('admin_user', models.CharField(blank=True, help_text='Admin who performed the action', max_length=100, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the action', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='menu.review')),
            ],
            options={
                'verbose_name': 'Izoh Harakati',
                'verbose_name_plural': 'Izoh Harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
