# Generated by Django 4.2.7 on 2025-10-03 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_cartitem_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='menu.review'),
        ),
    ]
