# Generated by Django 4.2.7 on 2025-10-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_reviewaction_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether the review has been deleted'),
        ),
    ]
