# Generated by Django 4.2.7 on 2025-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_review_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='content_type',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('menu', 'Menu Page'), ('about', 'About Section'), ('contact', 'Contact Section'), ('footer', 'Footer'), ('header', 'Header'), ('general', 'General'), ('notifications', 'Notifications & Messages'), ('forms', 'Form Labels & Buttons'), ('errors', 'Error Messages'), ('success', 'Success Messages')], max_length=20),
        ),
    ]
