# Generated by Django 4.2.7 on 2025-10-05 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_textcontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
        ),
    ]
