# Generated by Django 4.2.7 on 2025-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_promotion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
    ]
