# Generated by Django 4.2.7 on 2025-10-06 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_category_is_active_menuitem_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='linked_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='menu.menuitem'),
        ),
    ]
