# Generated by Django 4.2.7 on 2025-10-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_promotion_linked_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='menu.review'),
        ),
    ]
