# Generated by Django 4.2.16 on 2025-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_redesign_promotion_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Tokyo Restaurant', max_length=200)),
                ('site_name_uz', models.CharField(default='Tokyo Restoran', max_length=200)),
                ('site_name_ru', models.CharField(default='Ресторан Tokyo', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Site logo image', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Site favicon', null=True, upload_to='site/')),
                ('phone', models.CharField(default='+998 91 433 11 10', help_text='Bron uchun telefon raqami', max_length=20)),
                ('delivery_phone', models.CharField(default='+998 94 231 10 10', help_text='Dostavka uchun telefon raqami', max_length=20)),
                ('telegram_bot', models.CharField(default='@PizzaCentr_Bot', help_text='Telegram bot username', max_length=50)),
                ('email', models.EmailField(default='info@tokyokafe.uz', max_length=254)),
                ('address', models.TextField(default="Toshkent sh., Amir Temur ko'chasi 15")),
                ('address_uz', models.TextField(default="Toshkent sh., Amir Temur ko'chasi 15")),
                ('address_ru', models.TextField(default='г. Ташкент, ул. Амира Темура 15')),
                ('working_hours', models.CharField(default='Har kuni: 09:00 - 23:00', max_length=100)),
                ('working_hours_uz', models.CharField(default='Har kuni: 09:00 - 23:00', max_length=100)),
                ('working_hours_ru', models.CharField(default='Ежедневно: 09:00 - 23:00', max_length=100)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Sozlamalari',
                'verbose_name_plural': 'Site Sozlamalari',
            },
        ),
    ]
